baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'ABC Widgets, Inc.'
[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
